//Topbar
export const REQUEST_TOPBAR_PENDING = 'REQUEST_TOPBAR_PENDING';
export const REQUEST_TOPBAR_SUCCESS = 'REQUEST_TOPBAR_SUCCESS';
export const REQUEST_TOPBAR_FAILED  = 'REQUEST_TOPBAR_FAILED';


//Sidebar
export const REQUEST_SIDEBAR_PENDING ='REQUEST_SIDEBAR_PENDING';
export const REQUEST_SIDEBAR_SUCCESS ='REQUEST_SIDEBAR_SUCCESS';
export const REQUEST_SIDEBAR_FAILED  ='REQUEST_SIDEBAR_FAILED';

export const REQUEST_SIDEBAR_C_PENDING ='REQUEST_SIDEBAR_C_PENDING';
export const REQUEST_SIDEBAR_C_SUCCESS ='REQUEST_SIDEBAR_C_SUCCESS';
export const REQUEST_SIDEBAR_C_FAILED  ='REQUEST_SIDEBAR_C_FAILED';


//BLog
export const REQUEST_BLOG_PENDING ='REQUEST_BLOG_PENDING';
export const REQUEST_BLOG_SUCCESS ='REQUEST_BLOG_SUCCESS';
export const REQUEST_BLOG_FAILED  ='REQUEST_BLOG_FAILED';

export const REQUEST_BLOG_C_PENDING ='REQUEST_BLOG_C_PENDING';
export const REQUEST_BLOG_C_SUCCESS ='REQUEST_BLOG_C_SUCCESS';
export const REQUEST_BLOG_C_FAILED  ='REQUEST_BLOG_C_FAILED';

export const REQUEST_BLOG_S_PENDING ='REQUEST_BLOG_S_PENDING';
export const REQUEST_BLOG_S_SUCCESS ='REQUEST_BLOG_S_SUCCESS';
export const REQUEST_BLOG_S_FAILED  ='REQUEST_BLOG_S_FAILED';


//MENU
export const REQUEST_CATEGORY_PENDING ='REQUEST_CATEGORY_PENDING';
export const REQUEST_CATEGORY_SUCCESS ='REQUEST_CATEGORY_SUCCESS';
export const REQUEST_CATEGORY_FAILED  ='REQUEST_CATEGORY_FAILED';

export const REQUEST_CATEGORY_C_PENDING ='REQUEST_CATEGORY_C_PENDING';
export const REQUEST_CATEGORY_C_SUCCESS ='REQUEST_CATEGORY_C_SUCCESS';
export const REQUEST_CATEGORY_C_FAILED  ='REQUEST_CATEGORY_C_FAILED';

export const POST_CATEGORY_PENDING ='POST_CATEGORY_PENDING';
export const POST_CATEGORY_SUCCESS ='POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_FAILED  ='POST_CATEGORY_FAILED';

export const DELETE_CATEGORY_PENDING ='DELETE_CATEGORY_PENDING';
export const DELETE_CATEGORY_SUCCESS ='DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED  ='DELETE_CATEGORY_FAILED';

export const SEARCH_CATEGORY_PENDING ='SEARCH_CATEGORY_PENDING';
export const SEARCH_CATEGORY_SUCCESS ='SEARCH_CATEGORY_SUCCESS';
export const SEARCH_CATEGORY_FAILED  ='SEARCH_CATEGORY_FAILED';

export const SELECT_UPDATE_CATEGORY  ='SELECT_UPDATE_CATEGORY';

export const UPDATE_CATEGORY_PENDING ='UPDATE_CATEGORY_PENDING';
export const UPDATE_CATEGORY_SUCCESS ='UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED  ='UPDATE_CATEGORY_FAILED';

export const CANCEL_UPDATE_CATEGORY = 'CANCEL_UPDATE_CATEGORY';

export const CLEAR_SEARCH_CATEGORY = 'CLEAR_SEARCH_CATEGORY';



//TAG
export const REQUEST_TAG_PENDING ='REQUEST_TAG_PENDING';
export const REQUEST_TAG_SUCCESS ='REQUEST_TAG_SUCCESS';
export const REQUEST_TAG_FAILED  ='REQUEST_TAG_FAILED';

export const REQUEST_TAG_C_PENDING ='REQUEST_TAG_C_PENDING';
export const REQUEST_TAG_C_SUCCESS ='REQUEST_TAG_C_SUCCESS';
export const REQUEST_TAG_C_FAILED  ='REQUEST_TAG_C_FAILED';

export const POST_TAG_PENDING ='POST_TAG_PENDING';
export const POST_TAG_SUCCESS ='POST_TAG_SUCCESS';
export const POST_TAG_FAILED  ='POST_TAG_FAILED';

export const DELETE_TAG_PENDING ='DELETE_TAG_PENDING';
export const DELETE_TAG_SUCCESS ='DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILED  ='DELETE_TAG_FAILED';

export const SEARCH_TAG_PENDING ='SEARCH_TAG_PENDING';
export const SEARCH_TAG_SUCCESS ='SEARCH_TAG_SUCCESS';
export const SEARCH_TAG_FAILED  ='SEARCH_TAG_FAILED';

export const SELECT_UPDATE_TAG  ='SELECT_UPDATE_TAG';

export const UPDATE_TAG_PENDING ='UPDATE_TAG_PENDING';
export const UPDATE_TAG_SUCCESS ='UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILED  ='UPDATE_TAG_FAILED';

export const CANCEL_UPDATE_TAG = 'CANCEL_UPDATE_TAG';

export const CLEAR_SEARCH_TAG = 'CLEAR_SEARCH_TAG';



//MENU1
export const REQUEST_MENU1_PENDING ='REQUEST_MENU1_PENDING';
export const REQUEST_MENU1_SUCCESS ='REQUEST_MENU1_SUCCESS';
export const REQUEST_MENU1_FAILED  ='REQUEST_MENU1_FAILED';

export const REQUEST_MENU1_C_PENDING ='REQUEST_MENU1_C_PENDING';
export const REQUEST_MENU1_C_SUCCESS ='REQUEST_MENU1_C_SUCCESS';
export const REQUEST_MENU1_C_FAILED  ='REQUEST_MENU1_C_FAILED';

export const POST_MENU1_PENDING ='POST_MENU1_PENDING';
export const POST_MENU1_SUCCESS ='POST_MENU1_SUCCESS';
export const POST_MENU1_FAILED  ='POST_MENU1_FAILED';

export const DELETE_MENU1_PENDING ='DELETE_MENU1_PENDING';
export const DELETE_MENU1_SUCCESS ='DELETE_MENU1_SUCCESS';
export const DELETE_MENU1_FAILED  ='DELETE_MENU1_FAILED';

export const SEARCH_MENU1_PENDING ='SEARCH_MENU1_PENDING';
export const SEARCH_MENU1_SUCCESS ='SEARCH_MENU1_SUCCESS';
export const SEARCH_MENU1_FAILED  ='SEARCH_MENU1_FAILED';

export const SELECT_UPDATE_MENU1  ='SELECT_UPDATE_MENU1';

export const UPDATE_MENU1_PENDING ='UPDATE_MENU1_PENDING';
export const UPDATE_MENU1_SUCCESS ='UPDATE_MENU1_SUCCESS';
export const UPDATE_MENU1_FAILED  ='UPDATE_MENU1_FAILED';

export const CANCEL_UPDATE_MENU1 = 'CANCEL_UPDATE_MENU1';

export const CLEAR_SEARCH_MENU1 = 'CLEAR_SEARCH_MENU1';


//MENU2
export const REQUEST_MENU2_PENDING ='REQUEST_MENU2_PENDING';
export const REQUEST_MENU2_SUCCESS ='REQUEST_MENU2_SUCCESS';
export const REQUEST_MENU2_FAILED  ='REQUEST_MENU2_FAILED';

export const REQUEST_MENU2_C_PENDING ='REQUEST_MENU2_C_PENDING';
export const REQUEST_MENU2_C_SUCCESS ='REQUEST_MENU2_C_SUCCESS';
export const REQUEST_MENU2_C_FAILED  ='REQUEST_MENU2_C_FAILED';

export const POST_MENU2_PENDING ='POST_MENU2_PENDING';
export const POST_MENU2_SUCCESS ='POST_MENU2_SUCCESS';
export const POST_MENU2_FAILED  ='POST_MENU2_FAILED';

export const DELETE_MENU2_PENDING ='DELETE_MENU2_PENDING';
export const DELETE_MENU2_SUCCESS ='DELETE_MENU2_SUCCESS';
export const DELETE_MENU2_FAILED  ='DELETE_MENU2_FAILED';

export const SEARCH_MENU2_PENDING ='SEARCH_MENU2_PENDING';
export const SEARCH_MENU2_SUCCESS ='SEARCH_MENU2_SUCCESS';
export const SEARCH_MENU2_FAILED  ='SEARCH_MENU2_FAILED';

export const SELECT_UPDATE_MENU2  ='SELECT_UPDATE_MENU2';

export const UPDATE_MENU2_PENDING ='UPDATE_MENU2_PENDING';
export const UPDATE_MENU2_SUCCESS ='UPDATE_MENU2_SUCCESS';
export const UPDATE_MENU2_FAILED  ='UPDATE_MENU2_FAILED';

export const CANCEL_UPDATE_MENU2 = 'CANCEL_UPDATE_MENU2';

export const CLEAR_SEARCH_MENU2 = 'CLEAR_SEARCH_MENU2';

export const SELECT_PARENT_MENU_NAME = 'SELECT_PARENT_MENU_NAME';

//PARENT MENU MODAL
export const REQUEST_PARENT_MENU_PENDING ='REQUEST_PARENT_MENU_PENDING';
export const REQUEST_PARENT_MENU_SUCCESS ='REQUEST_PARENT_MENU_SUCCESS';
export const REQUEST_PARENT_MENU_FAILED  ='REQUEST_PARENT_MENU_FAILED';

export const SEARCH_PARENT_MENU_PENDING ='SEARCH_PARENT_MENU_PENDING';
export const SEARCH_PARENT_MENU_SUCCESS ='SEARCH_PARENT_MENU_SUCCESS';
export const SEARCH_PARENT_MENU_FAILED  ='SEARCH_PARENT_MENU_FAILED';

export const CLOSE_PARENT_MENU_MODAL = 'CLOSE_PARENT_MENU_MODAL';

export const CLEAR_SEARCH_PARENT_MENU = 'CLEAR_SEARCH_PARENT_MENU';

export const SELECT_PARENT_MENU = 'SELECT_PARENT_MENU';

export const CLEAR_CREATE_MENU2 ='CLEAR_CREATE_MENU2';

//MENUCONFIG
export const SELECT_MENU_LEVEL = 'SELECT_MENU_LEVEL';