//HOME
export const SELECT_HOME_INDEX = 'SELECT_HOME_INDEX';

//Topbar
export const REQUEST_TOPBAR_PENDING = 'REQUEST_TOPBAR_PENDING';
export const REQUEST_TOPBAR_SUCCESS = 'REQUEST_TOPBAR_SUCCESS';
export const REQUEST_TOPBAR_FAILED  = 'REQUEST_TOPBAR_FAILED';


//Sidebar
export const REQUEST_SIDEBAR_PENDING ='REQUEST_SIDEBAR_PENDING';
export const REQUEST_SIDEBAR_SUCCESS ='REQUEST_SIDEBAR_SUCCESS';
export const REQUEST_SIDEBAR_FAILED  ='REQUEST_SIDEBAR_FAILED';

export const REQUEST_SIDEBAR_C_PENDING ='REQUEST_SIDEBAR_C_PENDING';
export const REQUEST_SIDEBAR_C_SUCCESS ='REQUEST_SIDEBAR_C_SUCCESS';
export const REQUEST_SIDEBAR_C_FAILED  ='REQUEST_SIDEBAR_C_FAILED';


//Bloglist
export const REQUEST_BLOGLIST_PENDING ='REQUEST_BLOGLIST_PENDING';
export const REQUEST_BLOGLIST_SUCCESS ='REQUEST_BLOGLIST_SUCCESS';
export const REQUEST_BLOGLIST_FAILED  ='REQUEST_BLOGLIST_FAILED';

export const REQUEST_BLOGLIST_C_PENDING ='REQUEST_BLOGLIST_C_PENDING';
export const REQUEST_BLOGLIST_C_SUCCESS ='REQUEST_BLOGLIST_C_SUCCESS';
export const REQUEST_BLOGLIST_C_FAILED  ='REQUEST_BLOGLIST_C_FAILED';

export const SEARCH_BLOGLIST_PENDING ='SEARCH_BLOGLIST_PENDING';
export const SEARCH_BLOGLIST_SUCCESS ='SEARCH_BLOGLIST_SUCCESS';
export const SEARCH_BLOGLIST_FAILED  ='SEARCH_BLOGLIST_FAILED';

export const CLEAR_SEARCH_BLOGLIST ='CLEAR_SEARCH_BLOGLIST';


//Blog
export const REQUEST_BLOG_C_PENDING ='REQUEST_BLOG_C_PENDING';
export const REQUEST_BLOG_C_SUCCESS ='REQUEST_BLOG_C_SUCCESS';
export const REQUEST_BLOG_C_FAILED  ='REQUEST_BLOG_C_FAILED';

export const REQUEST_BLOG_PENDING ='REQUEST_BLOG_PENDING';
export const REQUEST_BLOG_SUCCESS ='REQUEST_BLOG_SUCCESS';
export const REQUEST_BLOG_FAILED  ='REQUEST_BLOG_FAILED';


// export const REQUEST_BLOG_TAG_PENDING = 'REQUEST_BLOG_TAG_PENDING';
// export const REQUEST_BLOG_TAG_SUCCESS = 'REQUEST_BLOG_TAG_SUCCESS';
// export const REQUEST_BLOG_TAG_FAILED  = 'REQUEST_BLOG_TAG_FAILED';
// export const REQUEST_BLOG_TAG_C_PENDING = ' REQUEST_BLOG_TAG_C_PENDING';
// export const REQUEST_BLOG_TAG_C_SUCCESS = ' REQUEST_BLOG_TAG_C_SUCCESS';
// export const REQUEST_BLOG_TAG_C_FAILED  = ' REQUEST_BLOG_TAG_C_FAILED';

export const SELECT_CREATE_BLOG = 'SELECT_CREATE_BLOG';
export const SELECT_CREATE_BLOG_C ='SELECT_CREATE_BLOG_C';

export const SELECT_UPDATE_BLOG_CATEGORY = 'SELECT_UPDATE_BLOG_CATEGORY';
export const CLEAR_BLOG_CATEGORY = 'CLEAR_BLOG_CATEGORY';
export const CLEAR_SELECT_BLOG_CATEGORY = 'CLEAR_SELECT_BLOG_CATEGORY';

export const SELECT_ADD_BLOG_TAG ='SELECT_ADD_BLOG_TAG';
export const DELETE_BLOG_TAG ='DELETE_BLOG_TAG';
export const CLEAR_SELECT_BLOG_TAG ='CLEAR_SELECT_BLOG_TAG';

export const POST_BLOG_PENDING = 'POST_BLOG_PENDING';
export const POST_BLOG_SUCCESS = 'POST_BLOG_SUCCESS';
export const POST_BLOG_FAILED  = 'POST_BLOG_FAILED';

export const UPDATE_BLOG = 'UPDATE_BLOG';
export const EXIT_UPDATE_BLOG = 'EXIT_UPDATE_BLOG';

export const CLEAR_CREATE_BLOG_FLAG = 'CLEAR_CREATE_BLOG_FLAG';

export const INIT_SELECTED_BLOG_TAG = 'INIT_SELECTED_BLOG_TAG';

export const INIT_SELECTED_BLOG_CATEGORY ='INIT_SELECTED_BLOG_CATEGORY';

//MENU
export const REQUEST_CATEGORY_PENDING ='REQUEST_CATEGORY_PENDING';
export const REQUEST_CATEGORY_SUCCESS ='REQUEST_CATEGORY_SUCCESS';
export const REQUEST_CATEGORY_FAILED  ='REQUEST_CATEGORY_FAILED';

export const REQUEST_CATEGORY_C_PENDING ='REQUEST_CATEGORY_C_PENDING';
export const REQUEST_CATEGORY_C_SUCCESS ='REQUEST_CATEGORY_C_SUCCESS';
export const REQUEST_CATEGORY_C_FAILED  ='REQUEST_CATEGORY_C_FAILED';

export const POST_CATEGORY_PENDING ='POST_CATEGORY_PENDING';
export const POST_CATEGORY_SUCCESS ='POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_FAILED  ='POST_CATEGORY_FAILED';

export const DELETE_CATEGORY_PENDING ='DELETE_CATEGORY_PENDING';
export const DELETE_CATEGORY_SUCCESS ='DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED  ='DELETE_CATEGORY_FAILED';

export const SEARCH_CATEGORY_PENDING ='SEARCH_CATEGORY_PENDING';
export const SEARCH_CATEGORY_SUCCESS ='SEARCH_CATEGORY_SUCCESS';
export const SEARCH_CATEGORY_FAILED  ='SEARCH_CATEGORY_FAILED';

export const SELECT_UPDATE_CATEGORY  ='SELECT_UPDATE_CATEGORY';

export const UPDATE_CATEGORY_PENDING ='UPDATE_CATEGORY_PENDING';
export const UPDATE_CATEGORY_SUCCESS ='UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED  ='UPDATE_CATEGORY_FAILED';

export const CANCEL_UPDATE_CATEGORY = 'CANCEL_UPDATE_CATEGORY';

export const CLEAR_SEARCH_CATEGORY = 'CLEAR_SEARCH_CATEGORY';

export const ONCHANGE_UPDATE_BLOG_TITLE = 'ONCHANGE_UPDATE_BLOG_TITLE';
export const ONCHANGE_UPDATE_BLOG_DESC = 'ONCHANGE_UPDATE_BLOG_DESC';
export const ONCHANGE_UPDATE_BLOG_PATH = 'ONCHANGE_UPDATE_BLOG_PATH';
export const ONCHANGE_UPDATE_BLOG_SEQ = 'ONCHANGE_UPDATE_BLOG_SEQ';


export const INIT_UPDATE_BLOG_TITLE = 'INIT_UPDATE_BLOG_TITLE';
export const INIT_UPDATE_BLOG_DESC = 'INIT_UPDATE_BLOG_DESC';
export const INIT_UPDATE_BLOG_PATH = 'INIT_UPDATE_BLOG_PATH';
export const INIT_UPDATE_BLOG_SEQ = 'INIT_UPDATE_BLOG_SEQ';

export const UPDATE_BLOG_PENDING = 'UPDATE_BLOG_PENDING';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAILED  = 'UPDATE_BLOG_FAILED' ;

//TAG
export const REQUEST_TAG_PENDING ='REQUEST_TAG_PENDING';
export const REQUEST_TAG_SUCCESS ='REQUEST_TAG_SUCCESS';
export const REQUEST_TAG_FAILED  ='REQUEST_TAG_FAILED';

export const REQUEST_TAG_C_PENDING ='REQUEST_TAG_C_PENDING';
export const REQUEST_TAG_C_SUCCESS ='REQUEST_TAG_C_SUCCESS';
export const REQUEST_TAG_C_FAILED  ='REQUEST_TAG_C_FAILED';

export const POST_TAG_PENDING ='POST_TAG_PENDING';
export const POST_TAG_SUCCESS ='POST_TAG_SUCCESS';
export const POST_TAG_FAILED  ='POST_TAG_FAILED';

export const DELETE_TAG_PENDING ='DELETE_TAG_PENDING';
export const DELETE_TAG_SUCCESS ='DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILED  ='DELETE_TAG_FAILED';

export const SEARCH_TAG_PENDING ='SEARCH_TAG_PENDING';
export const SEARCH_TAG_SUCCESS ='SEARCH_TAG_SUCCESS';
export const SEARCH_TAG_FAILED  ='SEARCH_TAG_FAILED';

export const SELECT_UPDATE_TAG  ='SELECT_UPDATE_TAG';

export const UPDATE_TAG_PENDING ='UPDATE_TAG_PENDING';
export const UPDATE_TAG_SUCCESS ='UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILED  ='UPDATE_TAG_FAILED';

export const CANCEL_UPDATE_TAG = 'CANCEL_UPDATE_TAG';

export const CLEAR_SEARCH_TAG = 'CLEAR_SEARCH_TAG';



//MENU1
export const REQUEST_MENU1_PENDING ='REQUEST_MENU1_PENDING';
export const REQUEST_MENU1_SUCCESS ='REQUEST_MENU1_SUCCESS';
export const REQUEST_MENU1_FAILED  ='REQUEST_MENU1_FAILED';

export const REQUEST_MENU1_C_PENDING ='REQUEST_MENU1_C_PENDING';
export const REQUEST_MENU1_C_SUCCESS ='REQUEST_MENU1_C_SUCCESS';
export const REQUEST_MENU1_C_FAILED  ='REQUEST_MENU1_C_FAILED';

export const POST_MENU1_PENDING ='POST_MENU1_PENDING';
export const POST_MENU1_SUCCESS ='POST_MENU1_SUCCESS';
export const POST_MENU1_FAILED  ='POST_MENU1_FAILED';

export const DELETE_MENU1_PENDING ='DELETE_MENU1_PENDING';
export const DELETE_MENU1_SUCCESS ='DELETE_MENU1_SUCCESS';
export const DELETE_MENU1_FAILED  ='DELETE_MENU1_FAILED';

export const SEARCH_MENU1_PENDING ='SEARCH_MENU1_PENDING';
export const SEARCH_MENU1_SUCCESS ='SEARCH_MENU1_SUCCESS';
export const SEARCH_MENU1_FAILED  ='SEARCH_MENU1_FAILED';

export const SELECT_UPDATE_MENU1  ='SELECT_UPDATE_MENU1';

export const UPDATE_MENU1_PENDING ='UPDATE_MENU1_PENDING';
export const UPDATE_MENU1_SUCCESS ='UPDATE_MENU1_SUCCESS';
export const UPDATE_MENU1_FAILED  ='UPDATE_MENU1_FAILED';

export const CANCEL_UPDATE_MENU1 = 'CANCEL_UPDATE_MENU1';

export const CLEAR_SEARCH_MENU1 = 'CLEAR_SEARCH_MENU1';


//MENU2
export const REQUEST_MENU2_PENDING ='REQUEST_MENU2_PENDING';
export const REQUEST_MENU2_SUCCESS ='REQUEST_MENU2_SUCCESS';
export const REQUEST_MENU2_FAILED  ='REQUEST_MENU2_FAILED';

export const REQUEST_MENU2_C_PENDING ='REQUEST_MENU2_C_PENDING';
export const REQUEST_MENU2_C_SUCCESS ='REQUEST_MENU2_C_SUCCESS';
export const REQUEST_MENU2_C_FAILED  ='REQUEST_MENU2_C_FAILED';

export const POST_MENU2_PENDING ='POST_MENU2_PENDING';
export const POST_MENU2_SUCCESS ='POST_MENU2_SUCCESS';
export const POST_MENU2_FAILED  ='POST_MENU2_FAILED';

export const DELETE_MENU2_PENDING ='DELETE_MENU2_PENDING';
export const DELETE_MENU2_SUCCESS ='DELETE_MENU2_SUCCESS';
export const DELETE_MENU2_FAILED  ='DELETE_MENU2_FAILED';

export const SEARCH_MENU2_PENDING ='SEARCH_MENU2_PENDING';
export const SEARCH_MENU2_SUCCESS ='SEARCH_MENU2_SUCCESS';
export const SEARCH_MENU2_FAILED  ='SEARCH_MENU2_FAILED';

export const SELECT_UPDATE_MENU2  ='SELECT_UPDATE_MENU2';

export const UPDATE_MENU2_PENDING ='UPDATE_MENU2_PENDING';
export const UPDATE_MENU2_SUCCESS ='UPDATE_MENU2_SUCCESS';
export const UPDATE_MENU2_FAILED  ='UPDATE_MENU2_FAILED';

export const CANCEL_UPDATE_MENU2 = 'CANCEL_UPDATE_MENU2';

export const CLEAR_SEARCH_MENU2 = 'CLEAR_SEARCH_MENU2';

export const SELECT_CREATE_PARENT_MENU_NAME = 'SELECT_CREATE_PARENT_MENU_NAME';

export const SELECT_UPDATE_PARENT_MENU_NAME = 'SELECT_UPDATE_PARENT_MENU_NAME';

export const CLEAR_SELECT_PARENT_MENU ='CLEAR_SELECT_PARENT_MENU';

//PARENT MENU MODAL
export const REQUEST_PARENT_MENU_PENDING ='REQUEST_PARENT_MENU_PENDING';
export const REQUEST_PARENT_MENU_SUCCESS ='REQUEST_PARENT_MENU_SUCCESS';
export const REQUEST_PARENT_MENU_FAILED  ='REQUEST_PARENT_MENU_FAILED';

export const SEARCH_PARENT_MENU_PENDING ='SEARCH_PARENT_MENU_PENDING';
export const SEARCH_PARENT_MENU_SUCCESS ='SEARCH_PARENT_MENU_SUCCESS';
export const SEARCH_PARENT_MENU_FAILED  ='SEARCH_PARENT_MENU_FAILED';

export const CLOSE_PARENT_MENU_MODAL = 'CLOSE_PARENT_MENU_MODAL';

export const CLEAR_SEARCH_PARENT_MENU = 'CLEAR_SEARCH_PARENT_MENU';

export const SELECT_CREATE_PARENT_MENU = 'SELECT_CREATE_PARENT_MENU';

export const SELECT_UPDATE_PARENT_MENU = 'SELECT_UPDATE_PARENT_MENU';

export const CLEAR_CREATE_MENU2 ='CLEAR_CREATE_MENU2';

export const SET_NOT_ALLOW_UPDATE_PARENT_MENU_NAME = 'SET_NOT_ALLOW_UPDATE_PARENT_MENU_NAME';

//MENUCONFIG
export const SET_MENU_TAB_NOT_DISABLE = 'SET_MENU_TAB_NOT_DISABLE';

//TINY EDITOR
export const INIT_TINY_EDITOR = 'INIT_TINY_EDITOR';

//CATEGORY MODAL
export const REQUEST_CATEGORY_MODAL_PENDING	= 'REQUEST_CATEGORY_MODAL_PENDING';
export const REQUEST_CATEGORY_MODAL_SUCCESS	= 'REQUEST_CATEGORY_MODAL_SUCCESS';
export const REQUEST_CATEGORY_MODAL_FAILED	= 'REQUEST_CATEGORY_MODAL_FAILED';

export const CLOSE_CATEGORY_MODAL			= 'CLOSE_CATEGORY_MODAL';

export const SEARCH_CATEGORY_MODAL_PENDING	= 'SEARCH_CATEGORY_MODAL_PENDING';
export const SEARCH_CATEGORY_MODAL_SUCCESS	= 'SEARCH_CATEGORY_MODAL_SUCCESS';
export const SEARCH_CATEGORY_MODAL_FAILED	= 'SEARCH_CATEGORY_MODAL_FAILED';

export const CLEAR_SEARCH_CATEGORY_MODAL	= 'CLEAR_SEARCH_CATEGORY_MODAL';

export const SELECT_CATEGORY_MODAL			= 'SELECT_CATEGORY_MODAL';

//TAG MODAL
export const REQUEST_TAG_MODAL_PENDING	= 'REQUEST_TAG_MODAL_PENDING';
export const REQUEST_TAG_MODAL_SUCCESS	= 'REQUEST_TAG_MODAL_SUCCESS';
export const REQUEST_TAG_MODAL_FAILED	= 'REQUEST_TAG_MODAL_FAILED';

export const CLOSE_TAG_MODAL			= 'CLOSE_TAG_MODAL';

export const SEARCH_TAG_MODAL_PENDING	= 'SEARCH_TAG_MODAL_PENDING';
export const SEARCH_TAG_MODAL_SUCCESS	= 'SEARCH_TAG_MODAL_SUCCESS';
export const SEARCH_TAG_MODAL_FAILED	= 'SEARCH_TAG_MODAL_FAILED';

export const CLEAR_SEARCH_TAG_MODAL		= 'CLEAR_SEARCH_TAG_MODAL';

export const SELECT_TAG_MODAL			= 'SELECT_TAG_MODAL';